fix: Add all the console.* methods
I had an error:
TypeError: console.time is not a function. (In 'console.time("search indexing")'

This is because we do not proxify all the console's methods.

I took the list from MDN and added it there to avoid an issue.