fix: Disable Flipper in iOS release builds
This is needed to fix `ld: symbol(s) not found for architecture arm64`
error on iOS CI

This happens because Flipper is not meant to be built in release mode
and because ReactNative removed direct support for Flipper since latest
versions